/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mazenk.channelforwarder

import com.jtelegram.api.TelegramBotRegistry
import com.jtelegram.api.events.channel.ChannelPostEvent
import com.jtelegram.api.events.message.MessageEvent
import com.jtelegram.api.kotlin.events.on
import com.jtelegram.api.kotlin.registerBot
import com.jtelegram.api.update.PollingUpdateProvider
import com.mazenk.channelforwarder.command.linkCommand
import com.mazenk.channelforwarder.command.linksCommand
import com.mazenk.channelforwarder.listeners.channelListener
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
    val botRegistry = TelegramBotRegistry.builder()
            .updateProvider(PollingUpdateProvider.builder().build())
            .build()

    val bot = botRegistry.registerBot(GlobalContext.config.apiKey)

    bot.commandRegistry.registerCommand("link", linkCommand)
    bot.commandRegistry.registerCommand("links", linksCommand)

    bot.eventRegistry.on(ChannelPostEvent::class, channelListener)

    println("${bot.botInfo.username} has started")
}
